### ISSUE TITLE
cv2.cv.CV_CAP_PROP_FRAME_WIDTH doesn't exist in OpenCV 3

### ISSUE THREAD

**Issue by mbeyeler** [mbeyeler/opencv-python-blueprints#13]
Update code so it works with OpenCV 3.

**Comment by M-AMAIRI** [comment]
Hello ,

i have encountered this issue and i have solved it by : 

#Decrease frame size
cap.set(cv2.CAP_PROP_FRAME_WIDTH, 1000)
#cv2.CAP_PROP_FRAME_WIDTH
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 600)

Thanks :) ,
Moatez ,

**Comment by Suraj023** [comment]
> Hello ,
> 
> i have encountered this issue and i have solved it by :
> 
> #Decrease frame size
> cap.set(cv2.CAP_PROP_FRAME_WIDTH, 1000)
> #cv2.CAP_PROP_FRAME_WIDTH
> cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 600)
> 
> Thanks :) ,
> Moatez ,

I have also encountered this issue from your solution
