### ISSUE TITLE
 capture.set(cv2.CV_CAP_PROP_FRAME_HEIGHT, 480) ----> does not work in opencv3

### ISSUE THREAD

**Issue by github4f** [mbeyeler/opencv-python-blueprints#14]
Hi- it seems that " capture.set(cv2.CV_CAP_PROP_FRAME_HEIGHT, 480)" does not work with opencv3. I see the following error:

  File "chapter7.py", line 293, in <module>
    main()
  File "chapter7.py", line 282, in main
    capture.set(cv2.CV_CAP_PROP_FRAME_HEIGHT, 480)
AttributeError: 'module' object has no attribute 'CV_CAP_PROP_FRAME_HEIGHT'

I use python 2.7 and followed the following link for installation:
http://www.pyimagesearch.com/2016/12/19/install-opencv-3-on-macos-with-homebrew-the-easy-way/

**Comment by mbeyeler** [comment]
Thanks for the report. You are right, of course: It should say `cv2.CAP_PROP_FRAME_HEIGHT`. The width was correct, but the height had a typo. If you pull the latest changes from the `master` branch, you should be good to go.

**Comment by YarlingB** [comment]
jaja era para confirmar


2017-03-13 12:13 GMT-06:00 Farshad <notifications@github.com>:
