### ISSUE TITLE
could not align head

### ISSUE THREAD

**Issue by yogeshAhireSuresh** [mbeyeler/opencv-python-blueprints#20]
i am using opencv2 and python version 3.5.2
i had made some changes and now got some error as follows:

Warning: Testing is disabled
Could not find data file  datasets/faces_preprocessed.pkl
Could not align head (eye detection failed?)

**Comment by mbeyeler** [comment]
Hi, in order to get a file "datasets/faces_preprocessed.pkl" you need to follow the following steps (described [here](https://github.com/mbeyeler/opencv-python-blueprints/blob/master/chapter7/chapter7.py#L10)):
  1. Run the GUI in Training Mode to assemble a training set. Upon exiting
      the app will dump all assembled training samples to a pickle file
      "datasets/faces_training.pkl".
  2. Run the script train_test_mlp.py to train a MLP classifier on the
      dataset. This file will store the parameters of the trained MLP in
      a file "params/mlp.xml" and dump the preprocessed dataset to a
      pickle file "datasets/faces_preprocessed.pkl".
  3. Run the GUI in Testing Mode to apply the pre-trained MLP classifier
      to the live stream of the webcam.

In Step 1, when you take a snapshot, the algorithm is trying to find the location of your head and eyes using some default OpenCV Haar cascade classifiers. The eye cascade I used (see [here](https://github.com/mbeyeler/opencv-python-blueprints/blob/master/chapter7/chapter7.py#L72)) can sometimes be a bit finicky... Make sure your scene is well-lit, don't wear your glasses, and try to make big googly eyes. :wink:

You might be able to find a better cascade classifier [here](https://github.com/opencv/opencv/tree/master/data/haarcascades).

Best,
Michael

**Comment by yogeshAhireSuresh** [comment]
Thank you for your reply,
i tried running the changes, now it is working fine and it is creating the
pkl file also but when i am running the train_test_mlp.py it is showing
following error.

**Comment by mbeyeler** [comment]
Which error is that? The message didn't show up on [GitHub Issues](https://github.com/mbeyeler/opencv-python-blueprints/issues/20)...

If you get errors in "train_test_mlp.py", make sure you have added multiple training samples from every class (happy, sad, etc.).

**Comment by yogeshAhireSuresh** [comment]
RESTART:
C:\Users\yahir\Downloads\opencv-python-blueprints-master\chapter7\train_test_mlp.py
Loading data from datasets/faces_training.pkl
Loaded 4 training samples
Save preprocessed data to datasets/faces_preprocessed.pkl
Traceback (most recent call last):
  File
"C:\Users\yahir\Downloads\opencv-python-blueprints-master\chapter7\train_test_mlp.py",
line 68, in <module>
    main()
  File
"C:\Users\yahir\Downloads\opencv-python-blueprints-master\chapter7\train_test_mlp.py",
line 42, in main
    train_method=cv2.ANN_MLP_TRAIN_PARAMS_BACKPROP,
AttributeError: module 'cv2.cv2' has no attribute
'ANN_MLP_TRAIN_PARAMS_BACKPROP'



it is the error

**Comment by yogeshAhireSuresh** [comment]
i solved that error of mean in homebrew.py line no 139 (Just added m), the
error was that in the code there was only one parameter and the parameter
for mean was missing.
but now i am getting an error for ANN_MLP as follows:

RESTART:
C:\Users\yahir\Downloads\opencv-python-blueprints-master\chapter7\train_test_mlp.py
Loading data from datasets/faces_training.pkl
Loaded 4 training samples
Save preprocessed data to datasets/faces_preprocessed.pkl
Traceback (most recent call last):
  File
"C:\Users\yahir\Downloads\opencv-python-blueprints-master\chapter7\train_test_mlp.py",
line 68, in <module>
    main()
  File
"C:\Users\yahir\Downloads\opencv-python-blueprints-master\chapter7\train_test_mlp.py",
line 42, in main
    train_method=cv2.ANN_MLP_TRAIN_PARAMS_BACKPROP,
AttributeError: module 'cv2.cv2' has no attribute
'ANN_MLP_TRAIN_PARAMS_BACKPROP'


please guide me.

**Comment by yogeshAhireSuresh** [comment]
i solved the upper commented error also by adding ml like

train_method=cv2.ml.ANN_MLP_BACKPROP,

but now i am getting the following error while running train_test_mlp.py:

previously the code was :
# initialize MLP
    self.model = cv2.ANN_MLP()
    self.model.create(layer_sizes)

error which i got is :

1-hidden layer networks Traceback (most recent call last): File
"C:\Users\yahir\Downloads\opencv-python-blueprints-master\chapter7\train_test_mlp.py",
line 68, in <module> main() File
"C:\Users\yahir\Downloads\opencv-python-blueprints-master\chapter7\train_test_mlp.py",
line 54, in main MLP = MultiLayerPerceptron(layerSizes, labels) File
"C:\Users\yahir\Downloads\opencv-python-blueprints-master\chapter7\classifiers.py",
line 221, in __init__ self.model = cv2.ANN_MLP() AttributeError: module
'cv2.cv2' has no attribute 'ANN_MLP'


The changes i had did:
 self.model = cv2.ml.ANN_MLP_create(layer_sizes)   // Its the code which is
throwing error

the error i got again is:

Traceback (most recent call last):
  File
"C:\Users\yahir\Downloads\opencv-python-blueprints-master\chapter7\train_test_mlp.py",
line 68, in <module>
    main()
  File
"C:\Users\yahir\Downloads\opencv-python-blueprints-master\chapter7\train_test_mlp.py",
line 54, in main
    MLP = MultiLayerPerceptron(layerSizes, labels)
  File
"C:\Users\yahir\Downloads\opencv-python-blueprints-master\chapter7\classifiers.py",
line 221, in __init__
    self.model = cv2.ml.ANN_MLP_create(layer_sizes)
SystemError: <built-in function ANN_MLP_create> returned NULL without
setting an error

**Comment by yogeshAhireSuresh** [comment]
sir, i am not able to solvethe ANN_MLP error, as i am using python 3.5.2
with opencv2.
i created dataset with many snapshots for each emotion but i am having
problem while running train_test_mlp script.
the screenshot is attached.

**Comment by mbeyeler** [comment]
It sounds like the `layer_sizes` variable has invalid format - have you tried printing it? It should be a NumPy array with the number of neurons in each layer `np.array([n_input, n_hidden, n_output])`.
