### ISSUE TITLE
Chapter 5: Error too many values to unpack

### ISSUE THREAD

**Issue by teknomo** [mbeyeler/opencv-python-blueprints#21]
Using the sample video of Chapter 5, when it run, it produces error:
in main
    sal.get_proto_objects_map(use_otsu=False)))

  File "tracking.py", line 68, in advance_frame
    box_all = self._append_boxes_from_saliency(proto_objects_map, box_all)

  File "tracking.py", line 105, in _append_boxes_from_saliency
    cnt_sal, _ = cv2.findContours(proto_objects_map, 1, 2)

ValueError: too many values to unpack

**Comment by mbeyeler** [comment]
Hi, which version of OpenCV are you running? My guess is 3 and up. They recently changed the syntax for the `findContours` function. Try this:
```
_, cnt_sal, _= cv2.findContours(proto_objects_map, 1, 2)
```

This has already been addressed in our [Google Discussion Group](https://groups.google.com/forum/#!topic/opencv-python-blueprints/UAZ29eMtAuY). Check it out when you get a chance! You might find other useful tips & tricks.

Best,
Michael
