### ISSUE TITLE
wxPython blocks on EVT_TIMER (Windows)

### ISSUE THREAD

**Issue by mbeyeler** [mbeyeler/opencv-python-blueprints#4]
Observed on Windows 10, Python 2.7.8, wxPython 3.0.2.0: The wx.EVT_PAINT event is looping and is blocking the wx.EVT_TIMER event (Seem to be some such issues with wxPython: http://trac.wxwidgets.org/ticket/11980 for one). Initial picture shows up, but then the window is blocked, doesn't refresh, and doesn't respond to any actions.

**Comment by johnConsidine** [comment]
Yes the screen freezes on a picture of me, its like its stalling, how do i fix this?

**Comment by mbeyeler** [comment]
Closed #4 via fa4ec03fc8e943073b3727225e4304cd53da8943.
