### ISSUE TITLE
Move common code out of chapters

### ISSUE THREAD

**Issue by mbeyeler** [mbeyeler/opencv-python-blueprints#8]
For the sake of the book release all chapters are supposed to be self-contained. However, now that this code is on GitHub, it would make more sense to move common code (such as `gui.py`) out of chapter directories and into a `common` directory in order to avoid code duplication.

- [ ] Create `common` module
- [ ] Move `gui.py`
- [ ] Move `classifiers.py`

**Comment by AhshanHaleem** [comment]
Please sir fix your script issues as soon as possible
