### ISSUE TITLE
wxPython can't be installed on Mac OS X 10.11 El Capitan

### ISSUE THREAD

**Issue by mbeyeler** [mbeyeler/opencv-python-blueprints#9]
This is not a problem with the book code itself, but with the wxPython package, which is required for most chapters.

Apparently it's impossible to install wxPython on Mac OS X 10.11 El Capitan via common practices, resulting in the following error:

```
“wxPython3.0-osx-cocoa-py2.7.pkg” is damaged and can’t be opened. You should eject the disk image.
```

The bug is documented here:
http://stackoverflow.com/questions/34402303/install-wxpython-in-osx-10-11

There seems to be a workaround here:
http://davixx.fr/blog/2016/01/25/wxpython-on-os-x-el-capitan/

Try to get confirmation that the workaround works. Has anyone tried this??

If it works, include instructions in the doc to resolve this nasty issue, so that users won't get stuck in the future.

**Comment by KaroAntonio** [comment]
This worked on 10.11.16:

 sudo pip install --upgrade --trusted-host wxpython.org --pre -f http://wxpython.org/Phoenix/snapshot-builds/ wxPython_Phoenix

http://stackoverflow.com/questions/32284938/how-to-properly-install-wxpython

**Comment by mbeyeler** [comment]
Excellent, thanks for sharing!

**Comment by mbeyeler** [comment]
Finally added these instructions to the README.md.
